version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - rails-demo-bundle-v1-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v1-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: rails-demo-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run tests
          # https://github.com/rails/spring/pull/546 - Spring bug...
          command: DISABLE_SPRING=true bin/rails test
